In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [ ]:
df = pd.read_csv('d.csv') 
df.head(1)

                                        Name  ... rev_bis
0  L’Anse aux Meadows National Historic Site  ...     NaN

[1 rows x 15 columns]

In [ ]:
df.drop(['short_description','longitude','latitude','iso_code','rev_bis'],axis = 1, inplace = True)
df.head(1)

                                        Name  ...  transboundary
0  L’Anse aux Meadows National Historic Site  ...              0

[1 rows x 10 columns]

In [ ]:
df.date_end.isnull().sum()

1114

In [ ]:
df.date_end.fillna(0,inplace = True)   # 0 represents still status alive

In [ ]:
df.head()

                                        Name  ...  transboundary
0  L’Anse aux Meadows National Historic Site  ...              0
1                      Nahanni National Park  ...              0
2                          Galápagos Islands  ...              0
3                              City of Quito  ...              0
4                       Simien National Park  ...              0

[5 rows x 10 columns]

## Recent Historical Category

In [ ]:
df['date_inscribed'].max()

2021

In [ ]:
df[df['date_inscribed']==2021]

                                                   Name  ...  transboundary
1121                           Sítio Roberto Burle Marx  ...              0
1122  Settlement and Artificial Mummification of the...  ...              0
1123  Quanzhou: Emporium of the World in Song-Yuan C...  ...              0
1124   Sudanese style mosques in northern Côte d’Ivoire  ...              0
1125                                Cordouan Lighthouse  ...              0
1126            Nice, Winter Resort Town of the Riviera  ...              0
1127                               Ivindo National Park  ...              0
1128                   Colchic Rainforests and Wetlands  ...              0
1129                            Mathildenhöhe Darmstadt  ...              0
1130              ShUM Sites of Speyer, Worms and Mainz  ...              0
1131   Kakatiya Rudreshwara (Ramappa) Temple, Telangana  ...              0
1132                         Dholavira: a Harappan City  ...              0
1133                              Trans-Iranian Railway  ...              0
1134            Cultural Landscape of Hawraman/Uramanat  ...              0
1135           Padua’s fourteenth-century fresco cycles  ...              0
1136                           The Porticoes of Bologna  ...              0
1137  Amami-Oshima Island, Tokunoshima Island, North...  ...              0
1138          Jomon Prehistoric Sites in Northern Japan  ...              0
1139  As-Salt - The Place of Tolerance and Urban Hos...  ...              0
1140              Chankillo Archaeoastronomical Complex  ...              0
1141                         Getbol, Korean Tidal Flats  ...              0
1142                     Roșia Montană Mining Landscape  ...              0
1143        Petroglyphs of Lake Onega and the White Sea  ...              0
1144                                 Ḥimā Cultural Area  ...              0
1145  The works of Jože Plečnik in Ljubljana – Human...  ...              0
1146  Paseo del Prado and Buen Retiro, a landscape o...  ...              0
1147                       Kaeng Krachan Forest Complex  ...              0
1148                                   Arslantepe Mound  ...              0
1149             The Slate Landscape of Northwest Wales  ...              0
1150  The work of engineer Eladio Dieste: Church of ...  ...              0
1151                      The Great Spa Towns of Europe  ...              1
1152  Frontiers of the Roman Empire – The Danube Lim...  ...              1
1153                            Colonies of Benevolence  ...              1
1154  Frontiers of the Roman Empire – The Lower Germ...  ...              1

[34 rows x 10 columns]

In [ ]:
test = df[(df['date_inscribed']==2021) & (df['date_end'] == 0)]
test.count()

Name              34
date_inscribed    34
danger            34
date_end          34
area_hectares     29
category_long     34
category_short    34
Country name      34
Region            34
transboundary     34
dtype: int64

In [ ]:
test.groupby('Country name')['Name'].count().sort_values(ascending = False)

Country name
Iran (Islamic Republic of)                                                                           2
India                                                                                                2
France                                                                                               2
Germany                                                                                              2
Japan                                                                                                2
Italy                                                                                                2
Austria,Germany,Slovakia                                                                             1
Belgium,Netherlands                                                                                  1
Brazil                                                                                               1
Chile                                                                                                1
China                                                                                                1
Côte d'Ivoire                                                                                        1
Gabon                                                                                                1
Georgia                                                                                              1
Germany,Netherlands                                                                                  1
Uruguay                                                                                              1
United Kingdom of Great Britain and Northern Ireland                                                 1
Jordan                                                                                               1
Peru                                                                                                 1
Republic of Korea                                                                                    1
Romania                                                                                              1
Russian Federation                                                                                   1
Saudi Arabia                                                                                         1
Slovenia                                                                                             1
Spain                                                                                                1
Thailand                                                                                             1
Turkey                                                                                               1
Austria,Belgium,Czechia,France,Germany,Italy,United Kingdom of Great Britain and Northern Ireland    1
Name: Name, dtype: int64

## Oldest Historical Categories

In [ ]:
df['date_inscribed'].min()

1978

In [ ]:
df[df['date_inscribed']==1978]

                                         Name  ...  transboundary
0   L’Anse aux Meadows National Historic Site  ...              0
1                       Nahanni National Park  ...              0
2                           Galápagos Islands  ...              0
3                               City of Quito  ...              0
4                        Simien National Park  ...              0
5                Rock-Hewn Churches, Lalibela  ...              0
6                           Aachen Cathedral   ...              0
7                   Historic Centre of Kraków  ...              0
8      Wieliczka and Bochnia Royal Salt Mines  ...              0
9                             Island of Gorée  ...              0
10                   Mesa Verde National Park  ...              0
11                  Yellowstone National Park  ...              0

[12 rows x 10 columns]

Oldest ones (1978 ones only) which still carry historical status  = 8 of 12

In [ ]:
test = df[(df['date_inscribed']==1978) & (df['date_end'] == 0)]
test.count()

Name              8
date_inscribed    8
danger            8
date_end          8
area_hectares     8
category_long     8
category_short    8
Country name      8
Region            8
transboundary     8
dtype: int64

In [ ]:
test = df[(df['date_inscribed']==1978)]
test.count()

Name              12
date_inscribed    12
danger            12
date_end          12
area_hectares     12
category_long     12
category_short    12
Country name      12
Region            12
transboundary     12
dtype: int64

In [ ]:
test.groupby('Country name')['Name'].count().sort_values(ascending = False)

Country name
United States of America    2
Poland                      2
Ethiopia                    2
Ecuador                     2
Canada                      2
Senegal                     1
Germany                     1
Name: Name, dtype: int64

##t

In [ ]:
df[['Name','category_short','Country name','transboundary']].groupby(['Country name','category_short']).count()

                                                                   Name  transboundary
Country name                                       category_short
Afghanistan                                        C                  2              2
Albania                                            C                  2              2
Albania,Austria,Belgium,Bosnia and Herzegovina,... N                  1              1
Albania,North Macedonia                            C/N                1              1
Algeria                                            C                  6              6
...                                                                 ...            ...
Yemen                                              C                  3              3
                                                   N                  1              1
Zambia,Zimbabwe                                    N                  1              1
Zimbabwe                                           C                  3              3
                                                   N                  1              1

[293 rows x 2 columns]

In [ ]:
df[['Name','category_short','Country name','transboundary']].groupby('category_short').count()

                Name  Country name  transboundary
category_short
C                898           898            898
C/N               39            39             39
N                218           218            218

In [ ]:
df[['Name','category_short','Country name','transboundary']].groupby('transboundary').count()

               Name  category_short  Country name
transboundary
0              1112            1112          1112
1                43              43            43

In [ ]:
t = df[['Name','category_short','Country name','transboundary']].groupby('Country name').count().sort_values(by=['category_short'],ascending = False)
t.head()

              Name  category_short  transboundary
Country name
China           55              55             55
Italy           51              51             51
Spain           45              45             45
France          43              43             43
Germany         41              41             41

## One Specific Country

In [ ]:
df[df['Country name']=='India'].count()

Name              39
date_inscribed    39
danger            39
date_end          39
area_hectares     39
category_long     39
category_short    39
Country name      39
Region            39
transboundary     39
dtype: int64

In [ ]:
df[df['Country name']=='India']

                                                   Name  ...  transboundary
145                                        Ajanta Caves  ...              0
146                                        Ellora Caves  ...              0
147                                           Agra Fort  ...              0
148                                           Taj Mahal  ...              0
169                                 Sun Temple, Konârak  ...              0
170                 Group of Monuments at Mahabalipuram  ...              0
195                             Kaziranga National Park  ...              0
196                            Manas Wildlife Sanctuary  ...              0
197                              Keoladeo National Park  ...              0
219                        Churches and Convents of Goa  ...              0
220                        Khajuraho Group of Monuments  ...              0
221                         Group of Monuments at Hampi  ...              0
222                                      Fatehpur Sikri  ...              0
260                    Group of Monuments at Pattadakal  ...              0
261                                     Elephanta Caves  ...              0
262                          Great Living Chola Temples  ...              0
263                            Sundarbans National Park  ...              0
294   Nanda Devi and Valley of Flowers National Parks    ...              0
314                        Buddhist Monuments at Sanchi  ...              0
380                               Humayun's Tomb, Delhi  ...              0
381                 Qutb Minar and its Monuments, Delhi  ...              0
601                          Mountain Railways of India  ...              0
725               Mahabodhi Temple Complex at Bodh Gaya  ...              0
736                          Rock Shelters of Bhimbetka  ...              0
760   Chhatrapati Shivaji Terminus (formerly Victori...  ...              0
761              Champaner-Pavagadh Archaeological Park  ...              0
837                                    Red Fort Complex  ...              0
896                           The Jantar Mantar, Jaipur  ...              0
946                                       Western Ghats  ...              0
968                             Hill Forts of Rajasthan  ...              0
987   Rani-ki-Vav (the Queen’s Stepwell) at Patan, G...  ...              0
988     Great Himalayan National Park Conservation Area  ...              0
1038  Archaeological Site of Nalanda Mahavihara at N...  ...              0
1039                      Khangchendzonga National Park  ...              0
1062                         Historic City of Ahmadabad  ...              0
1080  Victorian Gothic and Art Deco Ensembles of Mumbai  ...              0
1104                             Jaipur City, Rajasthan  ...              0
1131   Kakatiya Rudreshwara (Ramappa) Temple, Telangana  ...              0
1132                         Dholavira: a Harappan City  ...              0

[39 rows x 10 columns]

In [ ]:
t = df[df['Country name']=='India']
t.groupby('')

## Largest One

In [ ]:
t = df.sort_values(by = ['area_hectares'],ascending = False)
t.head()

                                Name  ...  transboundary
1101   French Austral Lands and Seas  ...              0
899   Phoenix Islands Protected Area  ...              0
909                Papahānaumokuākea  ...              0
86                Great Barrier Reef  ...              0
2                  Galápagos Islands  ...              0

[5 rows x 10 columns]

In [ ]:
t.interpolate()

                                                   Name  ...  transboundary
1126            Nice, Winter Resort Town of the Riviera  ...              0
1142                     Roșia Montană Mining Landscape  ...              0
1145  The works of Jože Plečnik in Ljubljana – Human...  ...              0
1152  Frontiers of the Roman Empire – The Danube Lim...  ...              1
1154  Frontiers of the Roman Empire – The Lower Germ...  ...              1

[5 rows x 10 columns]